=== a-palatinus/monetica/data/galerija.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="galerija">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="djelo" type="TipDjelo"
                            minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="jedinstvenId">
            <xs:selector xpath="djelo"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="TipDjelo">
        <xs:all>
            <xs:element name="naslov"     type="TipNeprazniTekst"/>
            <xs:element name="autor"      type="TipNeprazniTekst"/>
            <xs:element name="tehnika"    type="TipNeprazniTekst"/>
            <xs:element name="godina"     type="TipGodina"/>
            <xs:element name="dimenzije"  type="xs:string"/>
            <xs:element name="kategorija" type="TipKategorija"/>
            <xs:element name="slika"      type="xs:string"/>
            <xs:element name="opis"       type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="TipPozitivniCijeli" use="required"/>
    </xs:complexType>

    <xs:simpleType name="TipPozitivniCijeli">
        <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>

    <xs:simpleType name="TipNeprazniTekst">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:pattern value=".*\S.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipGodina">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1800"/>
            <xs:maxInclusive value="2100"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="TipKategorija">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Slikarstvo"/>
            <xs:enumeration value="Fotografija"/>
            <xs:enumeration value="Crtež"/>
            <xs:enumeration value="Ostalo"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== a-palatinus/monetica/data/galerija.xml
<?xml version="1.0" encoding="UTF-8"?>
<gal:galerija xmlns:gal="http://monetica.hr/galerija" xmlns:rad="http://monetica.hr/radionice" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://monetica.hr/galerija galerija.xsd                                   http://monetica.hr/radionice radionice.xsd">

    <!-- ─── Radovi Društva Monetica ─── -->

    <gal:djelo id="1">
        <gal:naslov>Nikol</gal:naslov>
        <gal:autor>Marija Kovač</gal:autor>
        <gal:tehnika>Ulje na platnu</gal:tehnika>
        <gal:godina>2023</gal:godina>
        <gal:dimenzije>80 × 60 cm</gal:dimenzije>
        <gal:kategorija>Slikarstvo</gal:kategorija>
        <gal:slika>images/djela/djevojka.jfif</gal:slika>
        <gal:opis>Idiličan prizor djevojčice na plaži.</gal:opis>
    </gal:djelo>

    

    <gal:djelo id="3">
        <gal:naslov>Jaganjac</gal:naslov>
        <gal:autor>Valentina Ćurković</gal:autor>
        <gal:tehnika>Grafitna olovka</gal:tehnika>
        <gal:godina>2025</gal:godina>
        <gal:dimenzije>A3</gal:dimenzije>
        <gal:kategorija>Crtež</gal:kategorija>
        <gal:slika>images/djela/isus.jpg</gal:slika>
        <gal:opis>Portret Isusa Krista dok nosi križ.</gal:opis>
    </gal:djelo>

    <gal:djelo id="4">
        <gal:naslov>Konec</gal:naslov>
        <gal:autor>Jovica Durdev</gal:autor>
        <gal:tehnika>Akril na platnu</gal:tehnika>
        <gal:godina>2024</gal:godina>
        <gal:dimenzije>40 × 60 cm</gal:dimenzije>
        <gal:kategorija>Slikarstvo</gal:kategorija>
        <gal:slika>images/djela/konec.jpg</gal:slika>
        <gal:opis>Bogat zalazak Sunca nad jezerom.</gal:opis>
    </gal:djelo>

    <gal:djelo id="5">
        <gal:naslov>Plov u suton</gal:naslov>
        <gal:autor>Luka Tomić</gal:autor>
        <gal:tehnika>Akril na platnu</gal:tehnika>
        <gal:godina>2023</gal:godina>
        <gal:dimenzije>40 × 60 cm</gal:dimenzije>
        <gal:kategorija>Slikarstvo</gal:kategorija>
        <gal:slika>images/djela/suton.jpg</gal:slika>
        <gal:opis>Plov brodova kroz sutonske valove.</gal:opis>
    </gal:djelo>

    <gal:djelo id="6">
        <gal:naslov>Miris prirode</gal:naslov>
        <gal:autor>Ana Blažević</gal:autor>
        <gal:tehnika>Ulje na platnu</gal:tehnika>
        <gal:godina>2023</gal:godina>
        <gal:dimenzije>70 × 90 cm</gal:dimenzije>
        <gal:kategorija>Slikarstvo</gal:kategorija>
        <gal:slika>images/djela/priroda.jfif</gal:slika>
        <gal:opis>Prikaz mirnog proljetnog dana na seoskom imanju.</gal:opis>
    </gal:djelo>

    <gal:djelo id="7">
        <gal:naslov>Cveteki</gal:naslov>
        <gal:autor>Marko Jurić</gal:autor>
        <gal:tehnika>Ulje na platnu</gal:tehnika>
        <gal:godina>2021</gal:godina>
        <gal:dimenzije>35 × 60 cm</gal:dimenzije>
        <gal:kategorija>Slikarstvo</gal:kategorija>
        <gal:slika>images/djela/vaza.jfif</gal:slika>
        <gal:opis>Plava vaza obasjana prirodnim svijetlom s prozora.</gal:opis>
    </gal:djelo>

    <gal:djelo id="8">
        <gal:naslov>Neda Arnerić</gal:naslov>
        <gal:autor>Petar Dimitrijević</gal:autor>
        <gal:tehnika>Grafitna olovka</gal:tehnika>
        <gal:godina>2026</gal:godina>
        <gal:dimenzije>A4</gal:dimenzije>
        <gal:kategorija>Crtež</gal:kategorija>
        <gal:slika>images/djela/neda.jpg</gal:slika>
        <gal:opis>Portret poluprofila iz gornjeg rakursa.</gal:opis>
    </gal:djelo>

    <gal:djelo id="9">
        <gal:naslov>Zagrebačkim ulicama</gal:naslov>
        <gal:autor>Nika Gatić</gal:autor>
        <gal:tehnika>Fotografija</gal:tehnika>
        <gal:godina>2022</gal:godina>
        <gal:dimenzije/>
        <gal:kategorija>Fotografija</gal:kategorija>
        <gal:slika>images/djela/zg.jpg</gal:slika>
        <gal:opis>Fotografija usamljene zagrebačke ulice.</gal:opis>
    </gal:djelo>

    <!-- ─── Radionice i izložbe ─── -->

    <rad:radionica id="r1">
        <rad:naslov>Kolaž</rad:naslov>
        <rad:opis>Dvodnevna radionica stvaranja kreativnih kompozicija od kolaža. Idealna za mlađe uzraste.</rad:opis>
        <rad:slika>images/radionice/kolaz.jpg</rad:slika>
    </rad:radionica>

    <rad:radionica id="r2">
        <rad:naslov>Oblikovanje gline</rad:naslov>
        <rad:opis>Ubrzani tečaj izrade glinenog posuđa.</rad:opis>
        <rad:slika>images/radionice/glina.jpg</rad:slika>
    </rad:radionica>

    <rad:radionica id="r3">
        <rad:naslov>Glow in the dark</rad:naslov>
        <rad:opis>Nesvakidašnja radionica slikanja po platnu i tijelu pomoću boja koje svijetle u mraku.</rad:opis>
        <rad:slika>images/radionice/glow_paint.jpg</rad:slika>
    </rad:radionica>

    <rad:radionica id="r4">
        <rad:naslov>Out Draw</rad:naslov>
        <rad:opis>Opušteno crtanje na otvorenom uz dobru ekipu.</rad:opis>
        <rad:slika>images/radionice/crtanje_na_otvorenom.jpg</rad:slika>
    </rad:radionica>

    <rad:radionica id="r5">
        <rad:naslov>Face paint</rad:naslov>
        <rad:opis>Kreativna radionica slikanja po licu.</rad:opis>
        <rad:slika>images/radionice/face_paint.jpg</rad:slika>
    </rad:radionica>

    <rad:radionica id="r6">
        <rad:naslov>Garden paint</rad:naslov>
        <rad:opis>Slikanje pejzaža uz stvarnu referencu, slikanje u vrtu.</rad:opis>
        <rad:slika>images/radionice/slikanje_u_vrtu.jpg</rad:slika>
    </rad:radionica>

</gal:galerija>
